import numpy as np
import matplotlib.pyplot as plt

# 1. Generate a noisy sine wave
samples = 100
t = np.linspace(0, 1, samples)
clean_signal = np.sin(2 * np.pi * 5 * t)  # 5 Hz sine wave
noise = np.random.normal(0, 0.3, samples) # Add random noise
noisy_signal = clean_signal + noise

# 2. Scale the signal
scaled_noisy = noisy_signal * 60 

# 3. Save to a hex file for Verilog to read
with open("input_data.hex", "w") as f:
    for val in scaled_noisy:
        # Convert to native Python int
        int_val = int(val)
        
        # Clamp to 8-bit signed integer limits to prevent overflow
        if int_val > 127: int_val = 127
        if int_val < -128: int_val = -128
            
        # Convert to 8-bit two's complement hex
        hex_val = f"{int_val & 0xFF:02x}"
        f.write(hex_val + "\n")

# 1. Read the output data generated by Verilog simulation
output_hex = []
with open("output_data.hex", "r") as f:
    for line in f:
        # Skip any 'xx' lines that happen while the filter pipeline is filling up
        if 'x' in line:
            output_hex.append(0)
            continue
            
        # Convert hex back to signed 8-bit integer
        val = int(line.strip(), 16)
        if val > 127:
            val -= 256
        output_hex.append(val)

# 2. Plot the Before and After
plt.figure(figsize=(10, 5))
plt.plot(scaled_noisy, label="Noisy Input (from Python)", color='red', alpha=0.6)
plt.plot(output_hex, label="Clean Output (from FPGA Simulation)", color='blue', linewidth=2)
plt.title("FPGA Real-Time Signal Denoising Simulation")
plt.xlabel("Time (Samples)")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.show()

print("Created input_data.hex!")
