module tb;
    // System signals: Clocking and 8-bit signed I/O
    reg clk = 0;
    reg signed [7:0] noisy_in;
    wire signed [7:0] clean_out;

    // Device Under Test (DUT) instantiation
    fir_filter dut (
        .clk(clk), 
        .noisy_in(noisy_in), 
        .clean_out(clean_out)
    );

    // Clock generation: 10ns period (100MHz simulation frequency)
    always #5 clk = ~clk;

    // Local buffer to hold 100 samples of synthetic telemetry from Python
    reg [7:0] memory [0:99]; 
    integer i, outfile;

    initial begin
        // Waveform dumping for post-simulation timing and logic analysis
        $dumpfile("dump.vcd"); 
        $dumpvars(0, tb);
        
        // Import noisy signal data generated by the Python preprocessing script
        $readmemh("input_data.hex", memory);
        
        // Establish an output file to capture filtered RTL results for HIL validation
        outfile = $fopen("output_data.hex", "w");

        // Synchronous data injection: streaming samples into the filter 
        // to observe real-time denoising and hardware latency.
        for (i = 0; i < 100; i = i + 1) begin
            noisy_in = memory[i];
            #10; // Allow one full clock cycle for the pipeline to process the sample
            
            // Log the processed hardware output for comparison against the Python model
            $fdisplay(outfile, "%h", clean_out);
        end
        
        // Cleanup: Closing data streams and terminating simulation
        $fclose(outfile);
        $finish;
    end
endmodule
