module tb;
    reg clk = 0;
    reg signed [7:0] noisy_in;
    wire signed [7:0] clean_out;

    // Instantiate the filter
    fir_filter dut (.clk(clk), .noisy_in(noisy_in), .clean_out(clean_out));

    // Generate Clock
    always #5 clk = ~clk;

    // Memory array to hold the 100 samples from Python
    reg [7:0] memory [0:99]; 
    integer i, outfile;

    initial begin
        $dumpfile("dump.vcd"); 
        $dumpvars(0, tb);
        
        // Read the noisy data generated by Python
        $readmemh("input_data.hex", memory);
        
        // Open a file to write the clean output
        outfile = $fopen("output_data.hex", "w");

        // Stream the data through the filter one clock cycle at a time
        for (i = 0; i < 100; i = i + 1) begin
            noisy_in = memory[i];
            #10; // Wait one full clock cycle
            
            // Write the filtered output to the file
            $fdisplay(outfile, "%h", clean_out);
        end
        
        $fclose(outfile);
        $finish;
    end
endmodule
